name: Vercel Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Pull Vercel Preview Environment
        if: github.ref == 'refs/heads/staging'
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Preview Deployment
        if: github.ref == 'refs/heads/staging'
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        if: github.ref == 'refs/heads/staging'
        run: npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Production Environment
        if: github.ref == 'refs/heads/main'
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Production Deployment
        if: github.ref == 'refs/heads/main'
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Production to Vercel
        if: github.ref == 'refs/heads/main'
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
